# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef00c988ad35149722ed7ec215f750ffb9c6ab32d2d865442f7ab386404f676f0214d73524332e8f995af8b3451e6ced20109dc17c2548e9bd2f716637cf511

test:
  secret_key_base: 03ca803bfbfbe54737aac7600fa31c3cd5b67f09acb36389cef4803ebb02ccf5eb275fc10d33e640eb520f056474b75a889020463fa1cccc168615eae74b99a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
